project:
  type: website

website:
  title: "TravisEz13"
  navbar:
    right:
      - about.qmd
      - disclaimer.qmd
      - icon: github
        href: https://github.com/travisez13
      - icon: twitter
        href: https://twitter.com/TravisPlunk
format:
  html:
    theme: darkly
    css: styles.css
