name: CI
on:
  pull_request:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
        - name: Lint markdown file
          uses: avto-dev/markdown-lint@v1
          with:
            config: './_action_files/mdlint.yml'
            args: '*.md'
