on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Quarto Publish

permissions:
  contents: read

jobs:
  deployment:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: cloudflare
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2.2

      - name: Render
        uses: quarto-dev/quarto-actions/render@8a96df13519ee81fd526f2dfca5962811136661b # v2.2
        with:
          path: quarto
          
      - name: Publish
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # 1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAT }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: travisez13
          directory: 'quarto/_site'
          
  render-only:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2.2

      - name: Render
        uses: quarto-dev/quarto-actions/render@8a96df13519ee81fd526f2dfca5962811136661b # v2.2
        with:
          path: quarto
          
