on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Quarto Publish

permissions:
  contents: read

jobs:
  deployment:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: cloudflare
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2.1.4

      - name: Render
        uses: quarto-dev/quarto-actions/render@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2.1.4
        with:
          path: quarto
          
      - name: Publish
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # 1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAT }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: travisez13
          directory: 'quarto/_site'
          
  render-only:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2.1.4

      - name: Render
        uses: quarto-dev/quarto-actions/render@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2.1.4
        with:
          path: quarto
          
